cobuildlab/cobuildlab-web

- src/assets/css/index.css
- src/components/footer.js
- src/pages/blog/education/index.js
- src/pages/blog/miami/index.js
- src/pages/blog/news/index.js
- src/pages/blog/small-business/index.js
- src/pages/blog/tools/index.js
- src/pages/index.js
- src/pages/privacy-policy/index.js
- src/templates/blog-post.js
> cambios conversados landing y blog privacy

- src/pages/blog/review-devfest-2019.md
> DevFest Review 2019 updated title

- src/pages/blog/review-devfest-2019.md
> devfest review title update

- src/components/TTSVoice.js
> pausing articles

- src/components/TTSVoice.js
- src/resources/icons/play-circle-solid.svg
- src/resources/icons/stop-circle-solid.svg
- src/templates/blog.js
New Voice Button with Icons, and new Layout
> New Voice Button and Layout

- src/pages/blog/artificial-intelligence-for-enterprise-software.md
> Dev corrección del post de ai y enterprise 

- src/components/enterprise/containers/footer/index.js
- src/components/enterprise/containers/menu/Sider.js
fixed: add ssr support to sider
> fixed: add suport to sider for ssr

- src/components/2020/Typography/css/index.module.scss
- src/components/2020/Typography/index.js
> fixed typography component

- package.json
- src/components/2020/CustomerSuccessStories/index.js
- src/components/enterprise/containers/brands/index.js
- src/components/enterprise/containers/testimonial/testimonial.js
- src/pages/index.js
fixed slick carousel scss import
> fixed slick-carousel scss

- gatsby-config.js
- package-lock.json
- package.json
- src/components/enterprise/containers/Menu.js
added gatsby-plugin-styled-components
> plugin for styled added

- package-lock.json
- src/components/2020/BadgeIndustry.js
- src/pages/apps-development-description.js
wrap landing page with container
> Container for page

- src/components/Typography/CardTitle.js
- src/components/Typography/H1.js
- src/components/Typography/H2.js
- src/components/Typography/H3.js
- src/components/Typography/H4.js
- src/components/Typography/H5.js
- src/components/Typography/IconTitlte.js
- src/components/Typography/Paragraph.js
- src/components/Typography/TextHelpers.js
added semi-colon to typography components for can add more styles
> Fixed typograph

- src/pages/apps-development-description.js
- src/pages/apps-development-graphic.js
create BannerWrapper component
import BannerBackground component
> banner error fixed

- src/components/BlogIndexAlt.js
- src/components/headerPost.js
- src/components/layoutPost.js
- src/pages/blog/education/index.js
- src/pages/blog/index.js
- src/pages/blog/miami/index.js
- src/pages/blog/news/index.js
- src/pages/blog/small-business/index.js
- src/pages/blog/tools/index.js
- src/templates/blog.js
design 2020 to blog
#311 
add typograhy to blog post
> design 2020 to blog pages

- src/components/NewsletterModal.js
> zIndex fixed

- src/components/NewsletterModal.js
> show modal after 30 seconds

- src/components/NewsletterModal.js
- src/components/Typography/H1.js
- src/pages/blog/index.js
fix newsLetterModal
fix blog title size
> fix modal responsive, fix blog title size

- src/components/2020/Header/index.js
- src/components/NewsletterModal.js
- src/components/enterprise/containers/footer/Footer.js
- src/components/portfolio/HeroTitle.js
- src/components/portfolio/Mansory/MansoryLayout.js
- src/components/portfolio/PortfolioLayout.js
- src/components/portfolio/PortfolioMenu.js
- src/components/portfolio/PortfolioMenuItems.js
- src/components/portfolio/ProjectContainer.js
- src/pages/portfolio.js
Fix portfolio footer problem
Add more time for newsletters ( 60 sec )
> fix portfolio / edit time in newsletters

- src/components/pdf/styles.js
> fix import font in react-pdf

- .env.development
- .env.production
Fix enviroment api contact key name
> fix enviroment api key name

- src/pages/blog/neocis.md
> FIX image copy on  neocis.md

- src/components/2020/header/Header.js
- src/components/2020/value/ValueCardFooter.js
- src/pages/2020/index.js
> fix buttons

- src/pages/blog/3-apps-that-we-enjoyed-developing-at-cobuild-lab.md
- PR # :
- PR # :
1. Issue # :
1. Issue # : 
1. Issue # : 
> (Prueba de carrusel 1) 3-apps-that-we-enjoyed-developing-at-cobuild-lab.md

- src/pages/team.js
- PR # :
- PR # :
1. Issue #444 :
> Update query on team view
1. Issue #: 
1. Issue # : 
> change querie for images on team view

- src/components/Carousel.js
- PR # : 
- PR # :
1. Issue # : Fix regexr for blog carousel
1. Issue # : 
1. Issue # : 
> fix carouse regexr

- src/assets/css/index.css
- src/components/blog-post/BlogTag.js
- src/pages/2018/assets/css/index.css
- src/pages/2019/assets/css/index.css
| Regular | Active | Hover |
| -- | -- | -- |
| Regular | Active | Hover |
| -- | -- | -- |
> New Tab Styles for Blog

- src/pages/blog/Profitable-Side-Jobs-for-Women-Struggling-in-the-Recession.md
- PR # :
- PR # :
1. Issue # :
1. Issue # : 
1. Issue # : 
> Marketing womenleg post

- src/components/2020/HomePageContact.js
- src/components/2020/header/Header.js
- src/pages/2020/index.js
- src/pages/apps-development-description.js
- src/pages/apps-development-graphic.js
- src/pages/apps-development-study-case.js
- src/pages/blog/education.js
- src/pages/blog/index.js
- src/pages/blog/miami.js
- src/pages/blog/news.js
- src/pages/blog/small-business.js
- src/pages/blog/tools.js
- src/pages/customer-success-stories.js
- src/pages/price-calculator.js
- src/pages/services.js
- src/pages/software-development-description.js
- src/pages/software-development-graphic.js
- src/pages/software-development-study-case.js
- src/pages/team.js
- src/pages/thanks-contact.js
- src/pages/thanks-newsletter.js
- PR # : Fix contact
- PR # :
1. Issue # :
1. Issue # : 
1. Issue # : 
> add form contact

- src/pages/blog/reasons-to-outsource-a-Software-development-team-instead-of-hiring-in-house.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> outsource a software team 

- src/pages/blog/Does-Your-Business-Need-an-App-3-Ways-to-Find-Out!.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> mobile app

- src/pages/blog/10-ways-to-increase-the-productivity-of-your-team-in-2020.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> 10 ways - productivity

- src/pages/blog/cobuild-lab-and-startup-bootkamp-will-teach-you-how-to-start-your-startup-this-october.md
- src/pages/blog/el-pitazo-and-cobuild-lab-joined-forces-to-build-a-software solution-to-keep-venezuelans-well-informed.md
Ya verifiqué, todo está como se esperaba. Check!
> PRESS RELEASE EL PITAZO

- src/pages/blog/Tips-for-Managing-the-Supply-Chain-after-a-Pandemic.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> tips supply chain

- src/pages/blog/5-Software-Trends-in-the-Logistic-Industry-You-Should-Know-for-2021.md
- src/pages/blog/8-Surprising-Things-About-Being-an-Entrepreneur-that-Nobody-Talks-About.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> logistics trends 2021

- src/components/2020/ContactForm.js
- src/components/enterprise/containers/contact/ContactEnterprise.js
- Issue #: https://github.com/cobuildlab/cobuildlab-web/issues/456
>  
- Issue #:  
>  
> 
- PR #
> 
-
> Crear pixel like technology para trackear de donde vienen los leads

- src/pages/blog/Technical-analysis-for-software-startup-investors.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Update Technical-analysis-for-software-startup-investors.md 

- src/pages/blog/4-readons-why-your-company-needs-a-custom-software.md
- src/pages/blog/Business-Partner-in-the-Software-World.md
- src/pages/blog/Strategies-I-Should-Prioritize-in-My-Business-for-2021.md
- src/pages/blog/product-development-process-for-software-products.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Marketing linkbuilding

- package.json
- src/components/enterprise/containers/contact/ContactEnterprise.js
- Issue #:https://github.com/cobuildlab/cobuildlab-web/issues/456
>  
- Issue #: 
>  
> 
- PR #
> 
-
> fix gatsby window.location is not defined

- src/components/services/card/ServicesCard.js
- src/pages/services.js
- Issue #: https://github.com/cobuildlab/cobuildlab-web/issues/533
>  
- Issue #:  https://github.com/cobuildlab/cobuildlab-web/issues/533
>  
> 
- PR #
> 
-
> - Page Services

- src/components/services/card/ServicesCard.js
- src/components/services/details/ServicesHeader.js
- src/pages/services.js
- src/pages/services/app-development.js
- src/pages/services/cross-platform-development.js
- src/pages/services/custom-customer-management-system.js
- src/pages/services/custom-learning-management-system.js
- src/pages/services/custom-software-development.js
- src/pages/services/digital-transformation.js
- src/pages/services/enterprise-software-development.js
- src/pages/services/field-service-management-system.js
- src/pages/services/mvp-software-development.js
- src/pages/services/process-automation.js
- src/pages/services/product-development.js
- src/pages/services/software-development.js
- src/pages/services/web-design.js
- src/pages/services/web-development.js
- Issue #: https://github.com/cobuildlab/cobuildlab-web/issues/533
>  
- Issue #: https://github.com/cobuildlab/cobuildlab-web/issues/533
>  
> 
- PR #
> 
-
> Page Services details

- src/components/customer-success-stories/new/DetailSection.js
- src/components/customer-success-stories/new/sliders/geeks-academy/Sliders.js
- src/components/customer-success-stories/new/sliders/jobcore/Sliders.js
- src/components/customer-success-stories/new/sliders/massone/Sliders.js
- src/components/customer-success-stories/new/sliders/my-voyce/Sliders.js
- src/components/customer-success-stories/new/sliders/payklever/Sliders.js
- src/components/customer-success-stories/new/sliders/propagad/Sliders.js
- src/components/customer-success-stories/new/sliders/weedmatch/Sliders.js
- src/components/services/card/ServicesCard.js
- src/pages/customer-success-stories/4geeks-academy.js
- src/pages/customer-success-stories/collabtogrow.js
- src/pages/customer-success-stories/el-pitazo.js
- src/pages/customer-success-stories/ezonseller.js
- src/pages/customer-success-stories/jobcore.js
- src/pages/customer-success-stories/massone.js
- src/pages/customer-success-stories/my-voice.js
- src/pages/customer-success-stories/okroo.js
- src/pages/customer-success-stories/payklever-campaign-manager.js
- src/pages/customer-success-stories/propagad.js
- src/pages/customer-success-stories/weedmatch.js
- Issue #: https://github.com/cobuildlab/cobuildlab-web/issues/564
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - Cambio de pluging de imagen en Customers Success Stories

- src/components/services/details/ServicesSection4.js
- src/pages/services/custom-software-development.js
- src/pages/services/digital-transformation.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - Services Detail, Digital Transformation content

- src/components/2021/containers/CompetitiveAdvantage.js
- src/components/2021/containers/Service2.js
- src/components/2021/containers/Video.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - FIX DESIGN HOME

- src/pages/blog/logistics-industry-trends-for-2021.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> New post. Logistics trends for 2021

- src/components/enterprise/containers/testimonial/Testimonial.js
- src/pages/blog/logistics-industry-trends-for-2021.md
- Fix home design
- fix date blog article
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Fix home design

- src/components/services/details/ServicesHeader.js
- src/components/services/details/ServicesSection2.js
- src/components/services/details/ServicesSection4.js
- src/pages/services/app-development.js
- src/pages/services/digital-transformation.js
- src/pages/services/enterprise-software-development.js
- src/pages/services/field-service-management-system.js
- digital transformation
- enterprise software development
- field services management system
- Issue #: https://github.com/cobuildlab/cobuildlab-web/issues/597
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - app development

- src/assets/css/index.css
- src/components/services/details/ServicesSection2.js
- src/pages/services.js
- src/pages/services/app-development.js
- src/pages/services/custom-software-development.js
- src/pages/services/enterprise-software-development.js
- src/pages/services/field-service-management-system.js
- src/pages/services/web-development.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - Adjust styles

- src/pages/blog/logistics-industry-trends-for-2021-part-2.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> [New Post] Blog: Logistics Industry Trends for 2021 (part 2)

- package-lock.json
- src/components/services/details/ServicesHeader.js
- src/components/services/details/ServicesSection2.js
- src/pages/services/app-development.js
- src/pages/services/cross-platform-development.js
- src/pages/services/custom-customer-management-system.js
- src/pages/services/custom-learning-management-system.js
- src/pages/services/custom-project-management-system.js
- src/pages/services/custom-software-development.js
- src/pages/services/digital-transformation.js
- src/pages/services/enterprise-software-development.js
- src/pages/services/field-service-management-system.js
- src/pages/services/it-support.js
- src/pages/services/mvp-software-development.js
- src/pages/services/process-automation.js
- src/pages/services/product-development.js
- src/pages/services/software-startup-investor.js
- src/pages/services/web-design.js
- src/pages/services/web-development.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Change imagen Services Detail

- src/components/services/details/ServicesHeader.js
- src/components/services/details/ServicesSection2.js
- src/components/services/details/ServicesSection4.js
- src/pages/services.js
- src/pages/services/app-development.js
- src/pages/services/cross-platform-development.js
- src/pages/services/custom-customer-management-system.js
- src/pages/services/digital-transformation.js
- src/pages/services/enterprise-software-development.js
- src/pages/services/it-support.js
- src/pages/services/mvp-software-development.js
- src/pages/services/process-automation.js
- src/pages/services/product-development.js
- src/pages/services/web-design.js
- src/pages/services/web-development.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - Fix services

- src/pages/services.js
- src/pages/services/custom-customer-management-system.js
- src/pages/services/custom-learning-management-system.js
- src/pages/services/custom-software-development.js
- src/pages/services/enterprise-software-development.js
- src/pages/services/software-startup-investor.js
- Issue #: #638 
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Change copy services

- src/components/services/ServicesHeader.js
- src/pages/services.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Change headers services

- src/assets/css/index.css
- src/components/2021/services/customer-success-stories/styled.js
- fix text CSS services
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - fix transition black background img

- src/components/2021/services/customer-success-stories/styled.js
- src/components/services/card/ServicesCard.js
- src/components/services/details/customer-success-stories/card/Avsee.js
- src/components/services/details/customer-success-stories/card/CollabToGrow.js
- src/components/services/details/customer-success-stories/card/GeeksAcademy.js
- src/components/services/details/customer-success-stories/card/JobCore.js
- src/components/services/details/customer-success-stories/card/LeadVolt.js
- src/components/services/details/customer-success-stories/card/Mama.js
- src/components/services/details/customer-success-stories/card/Massone.js
- src/components/services/details/customer-success-stories/card/MyVoice.js
- src/components/services/details/customer-success-stories/card/Okroo.js
- src/components/services/details/customer-success-stories/card/Payklever.js
- src/components/services/details/customer-success-stories/card/Pitazo.js
- src/components/services/details/customer-success-stories/card/Propagad.js
- src/components/services/details/customer-success-stories/card/Weedmatch.js
- src/pages/services.js
- src/pages/services/app-development.js
- src/pages/services/cross-platform-development.js
- src/pages/services/custom-customer-management-system.js
- src/pages/services/custom-learning-management-system.js
- src/pages/services/custom-project-management-system.js
- src/pages/services/custom-software-development.js
- src/pages/services/digital-transformation.js
- src/pages/services/enterprise-software-development.js
- src/pages/services/field-service-management-system.js
- src/pages/services/it-support.js
- src/pages/services/mvp-software-development.js
- src/pages/services/process-automation.js
- src/pages/services/web-development.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - Fix copy services

- src/assets/css/index.css
- src/components/services/card/ServicesCard.js
- src/pages/services/app-development.js
- src/pages/services/cross-platform-development.js
- src/pages/services/digital-transformation.js
- src/pages/services/mvp-software-development.js
- src/pages/services/web-design.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - Fix video youtube width

- src/pages/blog/reduce-your-headcount-with-the-help-of-machine-learning.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> new-post-machine-learning-employees

- src/components/2021/services/customer-success-stories/styled.js
- src/components/customer-success-stories/card/Card.js
- src/components/customer-success-stories/card/stories/Avsee.js
- src/components/customer-success-stories/card/stories/CollabToGrow.js
- src/components/customer-success-stories/card/stories/GeeksAcademy.js
- src/components/customer-success-stories/card/stories/JobCore.js
- src/components/customer-success-stories/card/stories/LeadVolt.js
- src/components/customer-success-stories/card/stories/Mama.js
- src/components/customer-success-stories/card/stories/Massone.js
- src/components/customer-success-stories/card/stories/MyVoice.js
- src/components/customer-success-stories/card/stories/Okroo.js
- src/components/customer-success-stories/card/stories/Payklever.js
- src/components/customer-success-stories/card/stories/Pitazo.js
- src/components/customer-success-stories/card/stories/Propagad.js
- src/components/customer-success-stories/card/stories/StoryRocket.js
- src/components/customer-success-stories/card/stories/Weedmatch.js
- src/components/services/details/customer-success-stories/card/Avsee.js
- src/components/services/details/customer-success-stories/card/CollabToGrow.js
- src/components/services/details/customer-success-stories/card/GeeksAcademy.js
- src/components/services/details/customer-success-stories/card/JobCore.js
- src/components/services/details/customer-success-stories/card/LeadVolt.js
- src/components/services/details/customer-success-stories/card/Mama.js
- src/components/services/details/customer-success-stories/card/Massone.js
- src/components/services/details/customer-success-stories/card/MyVoice.js
- src/components/services/details/customer-success-stories/card/Okroo.js
- src/components/services/details/customer-success-stories/card/Payklever.js
- src/components/services/details/customer-success-stories/card/Pitazo.js
- src/components/services/details/customer-success-stories/card/Propagad.js
- src/components/services/details/customer-success-stories/card/Weedmatch.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - Add Tag CSS

- src/components/blog-post/BlogHero.js
- src/components/customer-success-stories/card/stories/StoryRocket.js
- src/components/services/details/ServicesHeader.js
- src/components/services/details/ServicesSection2.js
- src/components/services/details/ServicesSection3.js
- src/components/services/details/ServicesSection4.js
- src/data/customer-success-stories-data.json
- src/pages/services/mvp-software-development.js
- src/pages/services/web-design.js
- Change title blog
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - change styles services section

- src/pages/blog/cloud-logistics-software-solution.md
- src/pages/blog/why-machine-learning-applied-to-the-supply-chain-will-save-the-planet.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> save the world

- src/pages/blog/internet-of-things-in-the-logistics-industry.md
- src/pages/blog/why-machine-learning-applied-to-the-supply-chain-will-save-the-planet.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Carolina barcelo save planet post

- src/pages/blog/why-machine-learning-applied-to-the-supply-chain-will-save-the-planet.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - fix blog extension images

- src/components/blog-post/BlogMetaTags.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Change title blog

- src/pages/blog/how-low-code-and-no-code-development-can-help-supply-chain-manager.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> fix image blog

- src/pages/services/digital-transformation.js
- src/pages/services/process-automation.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> change image services

- src/pages/blog/top-3-artificial-intelligence-benefits-that-will-revolutionize-your-company.md
Top 3 Artificial intelligence benefits  for businesses that will revolutionize your company
> New blog post June

- src/pages/blog/video-marketing.md
- src/pages/blog/what-is-digital-transformation-and-how-can-small-businesses-take-advantage-of-it-this-2020.md
- src/pages/blog/workflows-in-your-business.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> add new link in blog article

- gatsby-node.js
- src/components/logistics-landing/Banner.js
- src/dev.html.js
- add file index index dev
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - change description

- src/html.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> no index page in dev

- src/components/logistics-landing/Banner.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> spacing text

- src/pages/blog/cybersecurity-&-artificial-intelligence-how-can-they-benefit-your-business.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Fix blog - incorrect name template

- src/components/pdf/PdfCalculatorTemplate.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> fix pdf format currency price total

- gatsby-node.js
- package-lock.json
- package.json
- src/templates/blog-ai.amp.js
- src/templates/blog.amp.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Enabled AMP in blog and blog-ai

- gatsby-config.js
- gatsby-node.js
- src/components/blog-ai/BlogTagAI.js
- src/pages/blog/ai/financing.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Pagination

- src/components/blog-ai/BlogPostCardContainer.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> fix url pagination article

- src/components/blog-ai/BlogListAI.js
- src/components/blog-ai/search/client-search.js
- src/components/blog-post/BlogList.js
- src/components/blog-post/BlogTag.js
- src/pages/blog/ai/financing.js
- src/pages/blog/ai/index.js
- src/pages/blog/education.js
- src/pages/blog/index.js
- src/pages/blog/miami.js
- src/pages/blog/news.js
- src/pages/blog/small-business.js
- src/pages/blog/tools.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Blog search

- src/pages/blog/enterprise-software-solutions-tools.md
- src/pages/blog/methods-to-raise-funds-for-your-startup.md
- src/pages/blog/mistakes-that-kill-startups.md
- src/pages/blog/seo-tips-that-will-increase-your-position-in-search-engines.md
- src/pages/blog/what-is-digital-transformation-and-how-can-small-businesses-take-advantage-of-it-this-2020.md
- src/pages/blog/workflows-in-your-business.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Add link in article blog

- package-lock.json
- package.json
- src/assets/css/index.css
- src/components/Pagination.js
- src/components/blog-ai/BlogListAI.js
- src/components/blog-ai/search/client-search.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Add Pagination in blog

- src/components/portfolio/Mansory/Mansory.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> fix image portfolio

- src/components/2021/containers/Banner.js
- src/pages/index.js
- src/pages/services.js
- add link home page
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - hide services

- src/components/enterprise/containers/brands/index.js
- src/components/enterprise/containers/incubator/IncubatorImage.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Fix images Technology Stack

- src/components/services/ServicesTag.js
- src/components/services/card/ServicesCard.js
- src/components/services/details/ServicesSection2.js
- src/pages/services.js
- src/pages/services/low-code-or-no-code-development.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Feature/services - New UI

- src/pages/referrals.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> - referrals page seo

- src/pages/blog/How-Can-a-Mobile-or-Web-App-Help-Improve-the-Healthcare-Industry.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Add link article in blog

- src/pages/services.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Services re-organization

- src/pages/services/security-compliance.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Update Services security-compliance

- src/assets/css/index.css
- src/components/services/card/ServicesCard.js
- src/pages/services.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Fix font size services card

- src/pages/blog/Profitable-Side-Jobs-for-Women-Struggling-in-the-Recession.md
- src/pages/blog/Strategies-I-Should-Prioritize-in-My-Business-for-2021.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Add link in blog article

- src/components/services/ServicesTitle.js
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> h1 on Service page

- src/components/services/ServicesTitle.js
- src/components/services/details/ServicesHeader.js
- src/components/services/details/ServicesSection3.js
- src/pages/services/dashboard-development.js
- src/templates/careers.js
> Title hero is bold #953

- src/components/customer-success-stories/chart/GoalChart.js
- src/components/customer-success-stories/new/sliders/navigate/Sliders.js
- src/pages/customer-success-stories/navigate.js
Our goals section are already added.
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Main feature/882 new design of costumer success stories page

- src/pages/blog/new-product-development-for-small-business.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Nuevo post

- src/components/team/staff.js
fix name "Rossileydys" by "Rossileidys"
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> fix name Rossileidys our team page #992

- src/pages/customer-success-stories/art-play.js
Sections
- Issue #996:
>  
> 
- PR #
> 
-
> last section added #996

- src/components/customer-success-stories/new/sliders/art-play/Sliders.js
- src/pages/customer-success-stories/art-play.js
- Bugfix resize image carousel 
- Issue #996:
>  
> 
- PR #
> 
-
> bugfix resize image carousel #996

- src/components/customer-success-stories/detail-carousel/new/DetailCarousel.js
- carousel's image centered
- Issue #996:
>  
> 
- PR #
> 
-
> carousel's image centered #996

- src/templates/careers.js
- Dinamic SEO title and description.
- Issue #1015:
>  
> 
- PR #
> 
- 
```tsx
function CareersTemplate({ pageContext }) {
const { career } = pageContext;
const { title, description, jobProfile, responsibilities, requirements } = career;
return (
<Layout>
<SeoMetaTags
title={'Careers: ' + title}
description={`Careers for the Cobuild Lab - ${description}`}
/>
```
> Main feature/1015 positions should have a unique seo title

- src/pages/blog/five-reasons-to-develop-an-analytic-tool.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Marketing new post

- src/components/team/staff.js
- some staff member delete it
- Issue #1037 :
>  
> 
- PR #
> 
- 
https://www.loom.com/share/2e637b94c16045cf947a402258657909
> some staff member delete it

- src/pages/blog/robots-that-are-revolutionizing-the-world.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Marketing new post 

- src/pages/services/custom-customer-management-system.js
- src/pages/services/custom-inventory-management-system.js
- src/pages/services/custom-learning-management-system.js
- src/pages/services/custom-project-management-system.js
- src/pages/services/custom-software-development.js
- src/pages/services/field-service-management-system.js
- src/pages/services/it-staff-augmentation.js
- src/pages/services/it-support.js
- title and description has been changed, in the service pages.
- Issue #1056 :
>  
> 
- PR #
> 
-
> title and description has been changed, in the service pages.

- package-lock.json
- src/components/Typography/List.js
- src/components/input/CbTextArea.js
- src/components/referrals/ReferralBenefits.js
- src/components/referrals/ReferralsDisclaimer.js
- src/components/referrals/ReferralsHero.js
- src/components/referrals/ReferralsLeftSideHero.js
- src/components/referrals/ReferralsProgram.js
- src/components/referrals/ReferralsRightSideHero.js
- src/components/referrals/ReferralsTermsAndConditions.js
- src/pages/referrals.js
- Form desgning 90%.
- Section text added.
- Issue #1045 :
> 
- PR #
> 
-
> Main feature/1045 referals redesign

- src/components/2020/BannerBackground.js
- src/components/enterprise/containers/footer/FooterNavigation.js
- src/components/input/CbCheckbox.js
- src/components/input/CbTextArea.js
- src/components/referrals/ReferralBenefits.js
- src/components/referrals/ReferralsProgram.js
- src/components/referrals/ReferralsRightSideHero.js
- New link added at footer page.
- Issue #1075 :
> 
- PR #
> 
-
> Main feature/1075 link to referrals page

- src/templates/blog-ai.js
- styles added to the pre and code tags, spacing added.
- Issue #1092 :
> 
- PR #
> 
-
> styles added to the pre and code tags, spacing added.

- src/components/referrals/ReferralBenefits.js
- Text fixed
- Issue #1093 :
> 
- PR #
> 
-
> Text fixed

- src/components/referrals/ReferralBenefits.js
- text fixed again
- Issue #1093 :
> 
- PR #
> 
-
> text fixed again

- src/pages/customer-success-stories/fisherman.js
- Adjusment, Logical Architecture's text has been removed.
- Issue #1041 :
> 
- PR #
> 
-
> Main feature/css fisherman

- src/pages/customer-success-stories/fisherman.js
- src/pages/customer-success-stories/navigate.js
- Image meta tag page CSS Navigate fixed  
- Issue #1100:
> 
- PR #
> 
-
> Main feature/1100 css image meta tags

- src/pages/blog/do-you-really-know-what-coworking-is.md
- Link added.
- Issue #1102 :
> 
- PR #
> 
-
> Link added

- src/pages/blog/the-relationship-between-machine-learning-tools-and-data-annotation.md
- Title fixed
- Issue #1104 :
> 
- PR #
> 
-
> Title fixed

- src/templates/blog.js
- For the bold text the color indigo is.
- Issue #1123 :
> 
- PR #
> 
-
> For the bold text the color indigo is.

- src/docs/README.md
- Walkthrough videos done
- Issue #1251 :
> 
- PR #
> 
-
> [feature][main] #1251 Walkthrough videos done

- src/pages/blog/technical-analysis-for-software-investors.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> technical-analysis-for-software-investors.md

- src/pages/blog/role-of-a-full-stack-developer.md
- Issue #:
>  
- Issue #: 
>  
> 
- PR #
> 
-
> Marketing new posts

- src/pages/blog/cobuild-lab-inc-recognized-by-clutch-as-a-top-2022-ai-company-in-florida.md
- src/pages/blog/from-desk-to-dawn-how-the-remote-work-lifestyle-affect-productivity.md
- Fixed: path image's break line in quotes.
- Issue #1265  :
> 
- PR #
> 
-
> [bugfix][main] #1265 Fixed: path image's break line in quotes.
